name: Deployment - Reusable Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: Provide the deployment environment
        required: true
        default: dev
        type: string
      kubectl-version:
        description: Provide the required kubectl version
        required: false
        default: 'v1.30.0'
        type: string
      k8s-manifest-dir:
        description: Directory containing kubernetes manifest files
        required: true
        default: kubernetes/dev
        type: string
    outputs:
      application-url:
        value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL}}    
    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true

jobs:
  reuse-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ steps.set-ingress-host-url.outputs.APP_INGRESS_HOST }}        
    outputs:
      APP_INGRESS_URL: ${{ steps.set-ingress-host-url.outputs.APP_INGRESS_HOST }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Install kubectl CLI
      uses: azure/setup-kubectl@v4
      with:
        version: ${{ inputs.kubectl-version }}
        
    - name: Set Kubeconfig file
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.k8s-kubeconfig }}
        
    - name: Fetch kubernetes cluster details
      run: |
        kubectl version
        echo -------------------------------------------------------------
        kubectl get nodes
        
    - name: Save Nginx Ingress Controller IP as a Github environment variable
      run: >
        echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller 
        -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
    
    - name: Replace tokens in manifest files
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '_{_'
        tokenSuffix: '_}_'
        files: '["${{ inputs.k8s-manifest-dir }}/*.yaml"]'
      env:
        NAMESPACE: ${{ vars.NAMESPACE }}
        REPLICAS: ${{ vars.REPLICAS }}
        IMAGE: ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
        INGRESS_IP: ${{ env.INGRESS_IP }}

    - name: Check manifest files
      run: cat ${{ inputs.k8s-manifest-dir }}/*.yaml

    - name: Create MongoDB secret
      run: |
        kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
        --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
        --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
        --from-literal=MONGU_PASSWORD=${{ secrets.mongodb-password }} \
        --save-config \
        --dry-run=client \
        -o yaml | kubectl apply -f -

    - name: Deploy to ${{ inputs.environment }} environment
      run: kubectl apply -f ${{ inputs.k8s-manifest-dir }}

    - name: Set app ingress host URL
      id: set-ingress-host-url
      run: >
        echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress 
        -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_OUTPUT