name: Testing - Reusable Workflow

on:
  workflow_call:
    inputs:
      ingress-url:
        description: URL of the deployment to test
        required: true
        type: string

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Test URL output using curl and JQ
      env:
        URL: ${{ inputs.ingress-url }}
      continue-on-error: true
      timeout-minutes: 1
      run: |
        echo $URL
        echo "------------------------------------------"
        curl https://${URL}/live -s -k | jq -r ".status" | grep -i live